Change the name of the first author of assaad19a
mlresearch/v104 pull request #1
Opened 2022-06-15 06:14 UTC by thucmi

The first author of this paper recently changed his name from Karim Assaad to Charles K. Assaad. He requested to change his name on the paper as it will be important for his job.

The only thing that was changed is the name of the first author.

Thanks.

Thuc
V104 Editor.

2022-06-19 21:59 UTC, lawrennd requested changes
Hi Thuc, For this change to go through we need to change more than the PDF. 

You should go to the abstract page and click edit to access the page where the author name is stored.

Neil

2022-08-30 12:54 UTC, thucmi commented
Thanks Neil,

I have updated the bib file to reflect the changes.

Regards,
Thuc

2022-08-30 21:42 UTC, lawrennd commented
Hi Thuc,

Changing the anstract file doesn't propagate anything to the site, it is held for reference only. You need to click edit on the abstract page and it will take you to the right file.

2025-08-27 06:04 UTC, lawrennd commented
Just tidying up some old open requests. Will fix the posts entry here locally.

2025-08-27 06:04 UTC, merged